export const ActionTypes = {

    WEEK : {
        GET_WEEK_DATA : 'GET_WEEK_DATA'
    },
    EMPLOYEES: {
        GET_EMPLOYEES_DATA: "GET_EMPLOYEES_DATA",
        EMPLOYEES_DATA_FETCHED: "EMPLOYEES_DATA_FETCHED",
        FILTER: "FILTER"
    },
    SHIFTS: {
        GET_SHIFTS_DATA : "GET_SHIFTS_DATA",
        SHIFTS_DATA_FETCHED : "SHIFTS_DATA_FETCHED"
    }

};